// Synthetic-only owner page. No secrets, applicant data or public catalog link.
const page=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>GETHIRED owner interview</title><style>body{margin:0;background:#f7f5f0;color:#172b2b;font:16px/1.5 system-ui,Arial;padding:20px}main{max-width:680px;margin:20px auto;background:white;padding:clamp(22px,5vw,45px);border:1px solid #e0e2dc;border-radius:18px;box-shadow:0 14px 42px #22332210}h1{font-size:clamp(30px,5vw,44px);letter-spacing:-.04em;line-height:1.1;margin:18px 0}header,footer{color:#576761;border-bottom:1px solid #e1e5df;padding-bottom:14px}footer{border:0;border-top:1px solid #e1e5df;padding-top:20px;margin-top:38px;font-size:13px}.tag{font-size:12px;letter-spacing:.1em;text-transform:uppercase;font-weight:700}.note{background:#f5f5f0;border:1px solid #e5e7df;border-radius:10px;padding:15px;margin:22px 0}p{color:#4c5b5a}button,select{font:inherit;padding:12px;border-radius:9px;min-height:44px}button{background:#194437;color:white;border:0;cursor:pointer;margin:7px 8px 7px 0}button:disabled{background:#c7d0cb;color:#43534e}select{display:block;width:100%;border:1px solid #b5c2ba;background:white}.question{font-size:25px;color:#172b2b;line-height:1.35}.status{min-height:28px;color:#245742;font-weight:600}.error{color:#aa4038}.hidden{display:none}@media(max-width:460px){body{padding:8px}main{margin:3px auto}}</style></head><body><main><header class="tag">GETHIRED / PRIVATE OWNER TEST</header><h1>Interview sandbox</h1><p>Ask a live AI question for an invented role and applicant. This is not an application or hiring assessment.</p><div id="auth" class="note">Sign in from your private GETHIRED invitation email. This page does not send email.</div><section id="inside" class="hidden"><button id="logout" type="button">Sign out</button><label for="role">Fictional role</label><select id="role"><option value="sales">Salesperson / Fresher</option><option value="ml">AI / ML Engineer / Experienced</option></select><p class="note" id="profile"></p><button id="ask" type="button">Ask question 1</button><button id="next" type="button" disabled>Next fictional answer</button><p class="status" role="status" id="status"></p><p id="progress">Question 1 of 3</p><div id="answer" class="hidden"><span class="tag">AI-generated question</span><p id="question" class="question"></p><small id="skill"></small></div><div id="task" class="hidden"><span class="tag">Fictional task</span><p id="tasktext" class="question"></p></div></section><footer>Only fixed invented profiles and answers go to Groq. Nothing is saved as an applicant record. Up to 20 requests per UTC day; 20-second cooldown. No score or job decision.</footer></main><script>
const base='https://rlozvzlpapciwgointjp.supabase.co',key='sb_publishable_sux_sc3vuIg0SWTVlcCdqQ_l6VuVQQ1',owner='sankalpjaiswal2006@gmail.com';
const $=id=>document.getElementById(id),profiles={sales:'Nia is a fictional sales intern with simulated buyer discovery notes.',ml:'Ravi is a fictional ML engineer with simulated pipeline monitoring experience.'};let jwt='',step=0,role='sales';
function msg(x,bad=false){$('status').textContent=x;$('status').className=bad?'status error':'status'}
function reset(){step=0;$('ask').textContent='Ask question 1';$('ask').disabled=false;$('ask').classList.remove('hidden');$('next').disabled=true;$('answer').classList.add('hidden');$('task').classList.add('hidden');$('profile').textContent=profiles[role];$('progress').textContent='Question 1 of 3';msg('')}
function signout(){sessionStorage.removeItem('gethired_owner_jwt');jwt='';$('inside').classList.add('hidden');$('auth').textContent='Signed out. Sign in from your private GETHIRED invitation email.'}
async function session(t){const r=await fetch(base+'/auth/v1/user',{headers:{Authorization:'Bearer '+t,apikey:key}});if(!r.ok)throw Error('Sign-in link invalid or expired');const u=await r.json();if(u.email?.toLowerCase()!==owner||!u.email_confirmed_at)throw Error('Not the approved owner');jwt=t;sessionStorage.setItem('gethired_owner_jwt',t);$('inside').classList.remove('hidden');$('auth').textContent='Signed in as approved owner. Only invented test data below.';reset()}
async function ask(){if(!jwt)return;$('ask').disabled=true;$('next').disabled=true;msg('Generating a fictional question...');try{const p={fixtureId:role,step};if(step>0)p.answerId=step-1;const r=await fetch(base+'/functions/v1/gethired-owner-interview',{method:'POST',headers:{Authorization:'Bearer '+jwt,apikey:key,'Content-Type':'application/json'},body:JSON.stringify(p)});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');if(!d.synthetic||d.fixtureId!==role||!d.question)throw Error('Unexpected response');$('question').textContent=d.question;$('skill').textContent='Skill: '+d.competency;$('answer').classList.remove('hidden');$('progress').textContent='Question '+(step+1)+' of 3';$('ask').classList.add('hidden');$('next').disabled=false;msg('Fictional question ready')}catch(e){msg(e.message||'Request failed',true);$('ask').disabled=false}}
function next(){if(step===2){$('answer').classList.add('hidden');$('task').classList.remove('hidden');$('tasktext').textContent=role==='sales'?'Draft a fictional discovery note and respectful follow-up.':'Write a fictional investigation and rollback plan.';$('progress').textContent='3 of 3 questions, sample task shown';$('next').disabled=true;msg('No task submission here.');return}step++;$('ask').textContent='Ask question '+(step+1);$('ask').classList.remove('hidden');$('ask').disabled=false;$('next').disabled=true;$('answer').classList.add('hidden');msg('A predefined fictional answer will be used.')}
$('role').onchange=e=>{role=e.target.value;reset()};$('ask').onclick=ask;$('next').onclick=next;$('logout').onclick=signout;
const frag=new URLSearchParams(location.hash.slice(1)),t=frag.get('access_token')||sessionStorage.getItem('gethired_owner_jwt');if(location.hash)history.replaceState({},'',location.pathname);if(t)session(t).catch(e=>{signout();$('auth').textContent=e.message});
</script></body></html>`;
Deno.serve(req=>req.method==='GET'?new Response(page,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','X-Frame-Options':'DENY','Content-Security-Policy':"default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src https://rlozvzlpapciwgointjp.supabase.co; base-uri 'none'; form-action 'none'; frame-ancestors 'none'"}}):new Response('Method not allowed',{status:405}));
